package control;

public enum Actions {

	ADD_NEW_TURN, ACCEPT_FORMULARY_BUTTON,CANCEL_FORMULARY_BUTTON, EXPAND_BUTTON_DOWN,
	EXPAND_BUTTON_UP, SWITCH_DOWN_BUTTON_DIALOG, SWITCH_UP_BUTTON_DIALOG, LOAD_BUTTON,
	SAVE_BUTTON, NEXT_TURN_BUTTON, TURN_ITEM_SELECTED;
	
}
